[profile.default]
evm_version = "cancun"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
solc = "0.8.26"
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_forge'
optimizer_runs=999999
